2025-03-05 22:36:35,304 [ERROR] ETL-Test: Failed to import application components. Make sure the app package is in your PYTHONPATH.
2025-03-05 22:36:35,304 [ERROR] ETL-Test: Add the project root directory to PYTHONPATH or run this script from the project root.
2025-03-05 22:36:46,544 [ERROR] ETL-Test: Failed to import application components. Make sure the app package is in your PYTHONPATH.
2025-03-05 22:36:46,544 [ERROR] ETL-Test: Add the project root directory to PYTHONPATH or run this script from the project root.
2025-03-05 22:38:19,535 [ERROR] ETL-Test: Failed to import application components. Make sure the app package is in your PYTHONPATH.
2025-03-05 22:38:19,535 [ERROR] ETL-Test: Add the project root directory to PYTHONPATH or run this script from the project root.
2025-03-05 22:39:31,416 [ERROR] ETL-Test: Failed to import application components. Make sure the app package is in your PYTHONPATH.
2025-03-05 22:39:31,416 [ERROR] ETL-Test: Add the project root directory to PYTHONPATH or run this script from the project root.
2025-03-05 22:41:02,745 [ERROR] ETL-Test: Failed to import application components. Make sure the app package is in your PYTHONPATH.
2025-03-05 22:41:02,745 [ERROR] ETL-Test: Add the project root directory to PYTHONPATH or run this script from the project root.
2025-03-05 22:41:25,605 [ERROR] ETL-Test: Failed to import application components. Make sure the app package is in your PYTHONPATH.
2025-03-05 22:41:25,605 [ERROR] ETL-Test: Add the project root directory to PYTHONPATH or run this script from the project root.
2025-03-05 22:41:56,423 [ERROR] ETL-Test: Failed to import application components. Make sure the app package is in your PYTHONPATH.
2025-03-05 22:41:56,423 [ERROR] ETL-Test: Add the project root directory to PYTHONPATH or run this script from the project root.
2025-03-05 22:43:23,237 [ERROR] ETL-Test: Failed to import application components. Make sure the app package is in your PYTHONPATH.
2025-03-05 22:43:23,237 [ERROR] ETL-Test: Add the project root directory to PYTHONPATH or run this script from the project root.
2025-03-05 22:44:14,203 [ERROR] ETL-Test: Failed to import application components. Make sure the app package is in your PYTHONPATH.
2025-03-05 22:44:14,203 [ERROR] ETL-Test: Add the project root directory to PYTHONPATH or run this script from the project root.
2025-03-05 22:44:54,064 [ERROR] ETL-Test: Failed to import application components. Make sure the app package is in your PYTHONPATH.
2025-03-05 22:44:54,064 [ERROR] ETL-Test: Add the project root directory to PYTHONPATH or run this script from the project root.
2025-03-05 22:45:33,421 [INFO] ETL-Test: Starting ETL workflow tests in simple mode
2025-03-05 22:45:33,421 [INFO] ETL-Test: Current time: 2025-03-06 04:25:05, User: V1997
2025-03-05 22:45:33,422 [INFO] ETL-Test: Setting up ETL test environment
2025-03-05 22:45:33,519 [INFO] ETL-Test: Created test database at sqlite:///./test_etl.db
2025-03-05 22:45:33,519 [ERROR] core.batch_processor: Failed to initialize Kafka producer: name 'logger' is not defined
2025-03-05 22:45:33,524 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-03-05 22:45:33,525 [INFO] kafka.conn: Probing node bootstrap-0 broker version
2025-03-05 22:45:33,525 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-03-05 22:45:33,650 [INFO] kafka.conn: Broker version identified as 2.6.0
2025-03-05 22:45:33,650 [INFO] kafka.conn: Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
2025-03-05 22:45:33,651 [INFO] kafka.consumer.subscription_state: Updating subscribed topics to: ('etl-test-topic',)
2025-03-05 22:45:33,652 [INFO] ETL-Test: Connected to Kafka consumer at localhost:9092
2025-03-05 22:45:33,653 [INFO] ETL-Test: Test environment setup complete
2025-03-05 22:45:33,654 [INFO] ETL-Test: Starting happy path test
2025-03-05 22:45:33,668 [INFO] kafka.cluster: Group coordinator for etl-test-consumer-afc42242 is BrokerMetadata(nodeId='coordinator-0', host='host.docker.internal', port=9092, rack=None)
2025-03-05 22:45:33,669 [INFO] kafka.coordinator: Discovered coordinator coordinator-0 for group etl-test-consumer-afc42242
2025-03-05 22:45:33,669 [INFO] kafka.coordinator: Starting new heartbeat thread
2025-03-05 22:45:33,670 [INFO] kafka.coordinator.consumer: Revoking previously assigned partitions set() for group etl-test-consumer-afc42242
2025-03-05 22:45:33,673 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=coordinator-0 host=host.docker.internal:9092 <connecting> [IPv4 ('10.0.0.209', 9092)]>: connecting to host.docker.internal:9092 [('10.0.0.209', 9092) IPv4]
2025-03-05 22:45:33,674 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=coordinator-0 host=host.docker.internal:9092 <connecting> [IPv4 ('10.0.0.209', 9092)]>: Connection complete.
2025-03-05 22:45:33,674 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. 
2025-03-05 22:45:33,780 [INFO] kafka.coordinator: (Re-)joining group etl-test-consumer-afc42242
2025-03-05 22:45:33,781 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-03-05 22:45:33,781 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-03-05 22:45:33,786 [INFO] kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-03-05 22:45:33,787 [WARNING] kafka.coordinator.assignors.range: No partition metadata for topic etl-test-topic
2025-03-05 22:45:33,793 [INFO] kafka.coordinator: Successfully joined group etl-test-consumer-afc42242 with generation 1
2025-03-05 22:45:33,794 [INFO] kafka.consumer.subscription_state: Updated partition assignment: []
2025-03-05 22:45:33,794 [INFO] kafka.coordinator.consumer: Setting newly assigned partitions set() for group etl-test-consumer-afc42242
2025-03-05 22:45:33,902 [ERROR] core.batch_processor: Error processing batch BATCH-e51ce73f-1741236333: Error rate 100.00% exceeds threshold 20.00%
2025-03-05 22:45:33,903 [INFO] kafka.coordinator.consumer: Revoking previously assigned partitions set() for group etl-test-consumer-afc42242
2025-03-05 22:45:33,903 [INFO] kafka.coordinator: (Re-)joining group etl-test-consumer-afc42242
2025-03-05 22:45:33,903 [ERROR] core.batch_processor: Traceback (most recent call last):
  File "C:\Users\patel\Downloads\ETL Project\app\core\batch_processor.py", line 136, in process_batch
    raise ValueError(f"Error rate {error_rate:.2%} exceeds threshold {self.error_threshold:.2%}")
ValueError: Error rate 100.00% exceeds threshold 20.00%

2025-03-05 22:45:33,904 [INFO] kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-03-05 22:45:33,911 [INFO] kafka.coordinator: Successfully joined group etl-test-consumer-afc42242 with generation 2
2025-03-05 22:45:33,911 [INFO] kafka.consumer.subscription_state: Updated partition assignment: [TopicPartition(topic='etl-test-topic', partition=0)]
2025-03-05 22:45:33,912 [INFO] kafka.coordinator.consumer: Setting newly assigned partitions {TopicPartition(topic='etl-test-topic', partition=0)} for group etl-test-consumer-afc42242
2025-03-05 22:45:33,915 [INFO] ETL-Test: Cleaning up test environment
2025-03-05 22:45:33,923 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=0 host=host.docker.internal:9092 <connecting> [IPv4 ('10.0.0.209', 9092)]>: connecting to host.docker.internal:9092 [('10.0.0.209', 9092) IPv4]
2025-03-05 22:45:33,924 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=0 host=host.docker.internal:9092 <connecting> [IPv4 ('10.0.0.209', 9092)]>: Connection complete.
2025-03-05 22:45:33,925 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. 
2025-03-05 22:45:34,667 [INFO] kafka.coordinator: Stopping heartbeat thread
2025-03-05 22:45:34,667 [INFO] kafka.coordinator: Leaving consumer group (etl-test-consumer-afc42242).
2025-03-05 22:45:34,674 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=coordinator-0 host=host.docker.internal:9092 <connected> [IPv4 ('10.0.0.209', 9092)]>: Closing connection. 
2025-03-05 22:45:34,674 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=0 host=host.docker.internal:9092 <connected> [IPv4 ('10.0.0.209', 9092)]>: Closing connection. 
2025-03-05 22:45:34,676 [INFO] kafka.consumer.fetcher: Fetch to node 0 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.0.6, node_id=0 host=host.docker.internal:9092 <connected> [IPv4 ('10.0.0.209', 9092)]>
2025-03-05 22:54:12,456 [INFO] ETL-Test: Starting ETL workflow tests in simple mode
2025-03-05 22:54:12,456 [INFO] ETL-Test: Current time: 2025-03-06 04:51:53, User: V1997
2025-03-05 22:54:12,456 [INFO] ETL-Test: Setting up ETL test environment
2025-03-05 22:54:12,486 [INFO] ETL-Test: Created test database at sqlite:///./test_etl.db
2025-03-05 22:54:12,493 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-03-05 22:54:12,493 [INFO] kafka.conn: Probing node bootstrap-0 broker version
2025-03-05 22:54:12,494 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-03-05 22:54:12,615 [INFO] kafka.conn: Broker version identified as 2.6.0
2025-03-05 22:54:12,616 [INFO] kafka.conn: Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
2025-03-05 22:54:12,622 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=0 host=host.docker.internal:9092 <connecting> [IPv4 ('10.0.0.209', 9092)]>: connecting to host.docker.internal:9092 [('10.0.0.209', 9092) IPv4]
2025-03-05 22:54:12,624 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=0 host=host.docker.internal:9092 <connecting> [IPv4 ('10.0.0.209', 9092)]>: Connection complete.
2025-03-05 22:54:12,625 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. 
2025-03-05 22:54:12,629 [INFO] kafka.producer.kafka: Closing the Kafka producer with 4294967.0 secs timeout.
2025-03-05 22:54:12,630 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-producer-1, node_id=0 host=host.docker.internal:9092 <connected> [IPv4 ('10.0.0.209', 9092)]>: Closing connection. 
2025-03-05 22:54:12,630 [INFO] ETL-Test: Created or verified Kafka topic: etl-test-topic
2025-03-05 22:54:12,631 [ERROR] core.batch_processor: Failed to initialize Kafka producer: name 'logger' is not defined
2025-03-05 22:54:12,632 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
2025-03-05 22:54:12,633 [INFO] kafka.conn: Probing node bootstrap-0 broker version
2025-03-05 22:54:12,633 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connection complete.
2025-03-05 22:54:12,751 [INFO] kafka.conn: Broker version identified as 2.6.0
2025-03-05 22:54:12,752 [INFO] kafka.conn: Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
2025-03-05 22:54:12,753 [INFO] kafka.consumer.subscription_state: Updating subscribed topics to: ('etl-test-topic',)
2025-03-05 22:54:12,754 [INFO] ETL-Test: Connected to Kafka consumer at localhost:9092
2025-03-05 22:54:12,757 [INFO] kafka.cluster: Group coordinator for etl-test-consumer-927c61af is BrokerMetadata(nodeId='coordinator-0', host='host.docker.internal', port=9092, rack=None)
2025-03-05 22:54:12,758 [INFO] kafka.coordinator: Discovered coordinator coordinator-0 for group etl-test-consumer-927c61af
2025-03-05 22:54:12,760 [INFO] kafka.coordinator: Starting new heartbeat thread
2025-03-05 22:54:12,763 [INFO] kafka.coordinator.consumer: Revoking previously assigned partitions set() for group etl-test-consumer-927c61af
2025-03-05 22:54:12,764 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=coordinator-0 host=host.docker.internal:9092 <connecting> [IPv4 ('10.0.0.209', 9092)]>: connecting to host.docker.internal:9092 [('10.0.0.209', 9092) IPv4]
2025-03-05 22:54:12,765 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=coordinator-0 host=host.docker.internal:9092 <connecting> [IPv4 ('10.0.0.209', 9092)]>: Connection complete.
2025-03-05 22:54:12,766 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. 
2025-03-05 22:54:12,868 [INFO] kafka.coordinator: (Re-)joining group etl-test-consumer-927c61af
2025-03-05 22:54:12,877 [INFO] kafka.coordinator: Elected group leader -- performing partition assignments using range
2025-03-05 22:54:12,880 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=0 host=host.docker.internal:9092 <connecting> [IPv4 ('10.0.0.209', 9092)]>: connecting to host.docker.internal:9092 [('10.0.0.209', 9092) IPv4]
2025-03-05 22:54:12,881 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=0 host=host.docker.internal:9092 <connecting> [IPv4 ('10.0.0.209', 9092)]>: Connection complete.
2025-03-05 22:54:12,889 [INFO] kafka.coordinator: Successfully joined group etl-test-consumer-927c61af with generation 1
2025-03-05 22:54:12,891 [INFO] kafka.consumer.subscription_state: Updated partition assignment: [TopicPartition(topic='etl-test-topic', partition=0)]
2025-03-05 22:54:12,892 [INFO] kafka.coordinator.consumer: Setting newly assigned partitions {TopicPartition(topic='etl-test-topic', partition=0)} for group etl-test-consumer-927c61af
2025-03-05 22:54:12,901 [ERROR] ETL-Test: Error in Kafka consumer: Expecting value: line 1 column 1 (char 0)
2025-03-05 22:54:13,758 [INFO] ETL-Test: Test environment setup complete
2025-03-05 22:54:13,759 [INFO] ETL-Test: Starting happy path test
2025-03-05 22:54:13,844 [WARNING] ETL-Test: Generated data has 50 invalid records
2025-03-05 22:54:14,003 [INFO] ETL-Test: Cleaning up test environment
2025-03-05 22:54:14,009 [INFO] kafka.coordinator: Stopping heartbeat thread
2025-03-05 22:54:14,010 [INFO] kafka.coordinator: Leaving consumer group (etl-test-consumer-927c61af).
2025-03-05 22:54:14,017 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=coordinator-0 host=host.docker.internal:9092 <connected> [IPv4 ('10.0.0.209', 9092)]>: Closing connection. 
2025-03-05 22:54:14,018 [INFO] kafka.conn: <BrokerConnection client_id=kafka-python-2.0.6, node_id=0 host=host.docker.internal:9092 <connected> [IPv4 ('10.0.0.209', 9092)]>: Closing connection. 
2025-03-05 22:54:14,019 [WARNING] ETL-Test: Could not remove test database: [WinError 32] The process cannot access the file because it is being used by another process: './test_etl.db'
2025-03-05 22:54:14,020 [INFO] ETL-Test: Test environment cleanup complete
